### ISSUE TITLE
x11-libs/libdrm-armada does not build with =x11-base/xorg-server-1.19.2

### ISSUE THREAD

**Issue by mike01** [sakaki-/novena-overlay#3]
Compiling =x11-libs/libdrm-armada-0.2.0 with =x11-base/xorg-server-1.19.2 installed leads to a compilation error. I don't have the logs anymore but there seems to be some API change, among others a call to "BlockHandler". Compiling against downgraded to =x11-base/xorg-server-1.18.4 compiled again.

UPDATE:
Ok just retried it, attached are the logs leading to the error.
[xf86-video-armada-novena-0.0.1.16_build.log](https://github.com/sakaki-/novena-overlay/files/1396043/xf86-video-armada-novena-0.0.1.16_build.log)
Downgrade to =x11-base/xorg-server-1.18.4 works with =x11-libs/libdrm-armada-0.2.0.
